#!/bin/sh

#sudo git clone https://github.com/neslok/calm_flow.git

#sudo apt install -y apache2
#sudo apt install -y cifs-utils

setenforce 0

sudo yum install -y httpd
sudo systemctl start httpd
sudo yum install -y cifs-utils

sudo firewall-cmd --permanent --add-service=http
sudo firewall-cmd --permanent --add-service=https
sudo firewall-cmd --reload


#sudo mount -t cifs -o guest //$appIP/public/ /var/www/html/

#sudo sed -i '$ a ## cifs mount \n//$appIP/public   /var/www/html   cifs guest,uid=1000     0 0' /etc/fstab

sleep 1m
