#!/bin/sh


#sudo apt install -y tasksel
#sudo tasksel install samba-server

sudo yum install -y samba samba-client

sudo mv /etc/samba/smb.conf /etc/samba/smb.conf.orig
sudo git clone https://github.com/neslok/calm_flow.git
sudo mv calm_flow/smb.conf /etc/samba/smb.conf

sudo mkdir -p /mnt/samba/public
sudo chmod 777 /mnt/samba/public/

#sudo systemctl restart smbd

sudo firewall-cmd --permanent --zone=public --add-service=samba
sudo firewall-cmd --zone=public --add-service=samba
sudo firewall-cmd --reload

sudo systemctl start smb.service
sudo systemctl start nmb.service

#sudo apt install -y nfs-common

sudo yum install -y nfs-utils

##sudo mount -t nfs $dbIP:/mnt/nfs_share /mnt/samba/public/ ## moved to script in Calm

##sudo sed -i '$ a ## nfs mount \n $dbIP:/mnt/nfs_share     /samba/public   nfs defaults    0 0' /etc/fstab ## moved to script in Calm

sleep 1m


