#!/bin/sh

sudo apt install -y nfs-kernel-server
sudo mkdir -p /mnt/nfs_share
sudo chmod 777 /mnt/nfs_share/

sudo git clone https://github.com/neslok/calm_flow.git
sudo mv calm_flow/index.html /mnt/nfs_share

sudo apt install -y vsftpd
sudo mv /etc/vsftpd.conf /etc/vsftpd.conf.orig
sudo mv calm_flow/vsftpd.conf /etc/vsftpd.conf
sudo systemctl restart vsftpd


##sudo sed -i '$ a \n /mnt/nfs_share  *(rw,sync,no_root_squash,no_subtree_check)' /etc/exports

sudo systemctl restart nfs-kernel-server
